"use client";

import { useState } from "react";
import { getDirectReports, getSubordinateIds, type DashboardRole, type Profile } from "@/lib/permissions";
import { ModuleIcon, StatusBadge, type ModuleKey } from "@/components/qms";
import { SegmentedControl } from "@/components/ui/button";

type DashboardRecord = { id: string; assignedTo: string; status: string; module?: ModuleKey; title?: string; course?: string; dueDate?: string; date?: string; [key: string]: unknown };
type Records = Record<ModuleKey, DashboardRecord[]>;

const closedStatuses = ["Done", "Approved", "Closed"];
const modules: ModuleKey[] = ["documents", "capa", "nonconformances", "audits", "training"];
const isOpen = (record: DashboardRecord) => !closedStatuses.includes(record.status);
const recordLabel = (record: DashboardRecord) => record.title ?? String(record.course ?? record.id);
const isOverdue = (record: DashboardRecord) =>
  record.status === "Overdue" || (Boolean(record.dueDate) && new Date(record.dueDate as string) < new Date());

function ApprovalWidget({ records, viewerId, onSelect }: { records: DashboardRecord[]; viewerId: string; onSelect?: (r: DashboardRecord) => void }) {
  const pending = records.filter((record) => record.status === "Pending" && record.assignedTo !== viewerId);
  return <section className="rounded-2xl border border-[#D9A441]/40 bg-[#FFF9EA] p-4 dark:bg-[#2a2210] dark:border-[#7a5a1a]"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Pending my approval</h2><span className="rounded-full bg-[#D9A441] px-2 py-1 text-xs font-bold text-white">{pending.length}</span></div><div className="mt-3 space-y-2">{pending.length ? pending.slice(0, 5).map((record) => <button key={record.id} type="button" onClick={() => onSelect?.(record)} className="flex w-full items-center justify-between gap-3 rounded-xl bg-white p-3 text-left text-sm hover:bg-amber-50 dark:bg-slate-800 dark:hover:bg-slate-700"><span className="truncate text-slate-700 dark:text-slate-200">{recordLabel(record)}</span><StatusBadge status={record.status} /></button>) : <p className="text-sm text-slate-600 dark:text-slate-400">Nothing is waiting for your decision.</p>}</div></section>;
}

function Kpis({ records, title, onSelect }: { records: DashboardRecord[]; title: string; onSelect?: (m: ModuleKey) => void }) {
  const open = records.filter(isOpen);
  const count = (key: ModuleKey) => records.filter((record) => record.module === key && isOpen(record)).length;
  const overdueTraining = records.filter((record) => record.module === "training" && isOverdue(record)).length;
  return <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-900">{title}</h2><span className="text-sm text-slate-500">{open.length} open items</span></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Open CAPAs", count("capa"), "capa"], ["Open NCRs", count("nonconformances"), "nonconformances"], ["Open audits", count("audits"), "audits"], ["Overdue training", overdueTraining, "training"]].map(([label, value, module]) => <button key={String(label)} type="button" onClick={() => onSelect?.(module as ModuleKey)} className="rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:border-slate-300 hover:shadow-sm hover:-translate-y-[1px] active:scale-[0.98] dark:bg-slate-800 dark:border-slate-700 dark:hover:border-slate-600"><div className="flex items-center gap-2"><ModuleIcon moduleKey={module as ModuleKey} size="sm" /><div><p className="text-xs text-slate-500 dark:text-slate-400">{label}</p><p className="text-2xl font-bold text-slate-900 dark:text-slate-100">{value}</p></div></div></button>)}</div></section>;
}

function TeamRollups({ records, viewerId, profiles }: { records: DashboardRecord[]; viewerId: string; profiles: Profile[] }) {
  const directReports = getDirectReports(viewerId, profiles);
  return <section className="rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-lg font-semibold text-slate-900">By team</h2><div className="mt-3 space-y-3">{directReports.map((profile) => { const ids = [profile.id, ...getSubordinateIds(profile.id, profiles)]; const branch = records.filter((record) => ids.includes(record.assignedTo)); return <div key={profile.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="font-medium text-slate-700">{profile.name}</span><span className="text-sm text-slate-500">{branch.filter(isOpen).length} open / {branch.length} total</span></div>; })}</div></section>;
}

function PersonProgress({ profiles, records, viewerId }: { profiles: Profile[]; records: DashboardRecord[]; viewerId: string }) {
  const ids = [viewerId, ...getSubordinateIds(viewerId, profiles)];
  return <section className="rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-lg font-semibold text-slate-900">Team progress</h2><div className="mt-3 space-y-3">{profiles.filter((profile) => ids.includes(profile.id)).map((profile) => { const mine = records.filter((record) => record.assignedTo === profile.id); const done = mine.filter((record) => !isOpen(record)).length; const percentage = mine.length ? Math.round((done / mine.length) * 100) : 0; return <div key={profile.id}><div className="flex justify-between text-sm"><span>{profile.name}</span><span className="text-slate-500">{percentage}%</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#1E2530]" style={{ width: `${percentage}%` }} /></div></div>; })}</div></section>;
}

function Compliance({ records }: { records: DashboardRecord[] }) { const score = records.length ? Math.round((records.filter((record) => !isOpen(record)).length / records.length) * 100) : 0; return <section className="rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-lg font-semibold text-slate-900">Compliance score</h2><div className="mt-4 flex items-center justify-center"><div className="flex h-28 w-28 items-center justify-center rounded-full border-12 border-[#EDF4EF] text-center"><div><div className="text-3xl font-bold text-slate-900">{score}</div><div className="text-[10px] uppercase tracking-widest text-slate-500">score</div></div></div></div></section>; }

export function Dashboard({ viewerId, profiles, records, role, onModuleSelect, onRecordSelect }: { viewerId: string; profiles: Profile[]; records: Records; role: DashboardRole; onModuleSelect?: (m: ModuleKey) => void; onRecordSelect?: (r: DashboardRecord) => void }) {
  const [breakdown, setBreakdown] = useState<"team" | "person">("team");
  const allRecords = modules.flatMap((module) => (records[module] ?? []).map((record) => ({ ...record, module })));
  const scoped = allRecords.filter((record) => [viewerId, ...getSubordinateIds(viewerId, profiles)].includes(record.assignedTo));
  const directTeam = allRecords.filter((record) => getDirectReports(viewerId, profiles).map((profile) => profile.id).includes(record.assignedTo));
  if (role === "staff") return <div className="space-y-6"><Kpis records={scoped} title="My tasks" onSelect={onModuleSelect} /><div className="grid gap-4 sm:gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-4 dark:bg-slate-800 dark:border-slate-700"><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">My tasks</h2><div className="mt-3 space-y-2">{scoped.filter(isOpen).slice(0,6).map((record) => <button key={record.id} type="button" onClick={() => onRecordSelect ? onRecordSelect(record) : onModuleSelect?.(record.module as ModuleKey)} className="flex w-full justify-between rounded-xl bg-slate-50 p-3 text-left text-sm hover:bg-slate-100 dark:bg-slate-900 dark:hover:bg-slate-700"><span className="truncate dark:text-slate-200">{recordLabel(record)}</span><StatusBadge status={record.status} /></button>)}{scoped.filter(isOpen).length===0 && <p className="text-sm text-slate-500 dark:text-slate-400">No open tasks.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-4 dark:bg-slate-800 dark:border-slate-700"><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">My training status</h2><p className="mt-3 text-sm text-slate-600 dark:text-slate-400">{scoped.filter((record) => record.course || record.assignedTo).filter((record) => record.assignedTo === viewerId && record.course).filter(isOpen).length} training items remain open.</p><button type="button" onClick={() => onModuleSelect?.("training")} className="mt-3 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 dark:bg-white dark:text-slate-900">View training</button></section></div></div>;
  if (role === "process-owner") return <div className="space-y-6"><ApprovalWidget records={directTeam} viewerId={viewerId} onSelect={onRecordSelect} /><Kpis records={directTeam} title="Direct team" onSelect={onModuleSelect} /><div className="grid gap-4 sm:gap-6 xl:grid-cols-2"><PersonProgress profiles={profiles} records={directTeam} viewerId={viewerId} /><section className="rounded-2xl border border-[#C1614F]/30 bg-[#FFF5F3] p-4 dark:bg-[#2a1a1a] dark:border-[#7a2a2a]"><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Overdue items</h2><div className="mt-3 space-y-2">{directTeam.filter(isOverdue).slice(0,5).map((record) => <button key={record.id} type="button" onClick={() => onRecordSelect ? onRecordSelect(record) : onModuleSelect?.(record.module as ModuleKey)} className="w-full rounded-xl bg-white p-3 text-left text-sm text-[#C1614F] hover:bg-red-50 dark:bg-slate-800 dark:text-red-300">{recordLabel(record)}</button>)}{directTeam.filter(isOverdue).length===0 && <p className="text-sm text-slate-500 dark:text-slate-400">No overdue items.</p>}</div></section></div></div>;
  if (role === "team-lead") return <div className="space-y-6"><Kpis records={scoped} title="Full team subtree" onSelect={onModuleSelect} /><ApprovalWidget records={scoped} viewerId={viewerId} onSelect={onRecordSelect} /><div className="grid gap-4 sm:gap-6 xl:grid-cols-2"><TeamRollups records={scoped} viewerId={viewerId} profiles={profiles} /><PersonProgress profiles={profiles} records={scoped} viewerId={viewerId} /></div></div>;
  return <div className="space-y-6"><Kpis records={allRecords} title="Company-wide performance" onSelect={onModuleSelect} /><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Organization breakdown</h2><SegmentedControl value={breakdown} onChange={(v) => setBreakdown(v as "team" | "person")} options={[{ value: "team", label: "By team" }, { value: "person", label: "By person" }]} /></div><div className="grid gap-4 sm:gap-6 xl:grid-cols-[1.3fr_0.7fr]">{breakdown === "team" ? <TeamRollups records={allRecords} viewerId={viewerId} profiles={profiles} /> : <PersonProgress profiles={profiles} records={allRecords} viewerId={viewerId} />}<Compliance records={allRecords} /></div><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:bg-slate-800 dark:border-slate-700"><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Significant activity</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">New non-conformances and audit closures are highlighted here.</p></section></div>;
}
