import { makeCsv, makePdf, makePng } from "./qms-files";
import { recordsByModule } from "./qms-data";

/** A seeded file: written to the same columns the multipart upload API fills. */
export type SeedFile = {
  fileName: string;
  fileType: string;
  fileSize: number;
  fileData: string; // base64, same shape the upload route stores
};

const pdf = (title: string, lines: string[]): SeedFile => {
  const buf = makePdf(title, lines);
  return {
    fileName: `${title.replace(/[^\w-]+/g, "-").toLowerCase()}.pdf`,
    fileType: "application/pdf",
    fileSize: buf.byteLength,
    fileData: buf.toString("base64"),
  };
};

const csv = (name: string, rows: string[][]): SeedFile => {
  const buf = makeCsv(rows);
  return {
    fileName: name,
    fileType: "text/csv",
    fileSize: buf.byteLength,
    fileData: buf.toString("base64"),
  };
};

const docHeader = (id: string, rev: string, owner: string) => [
  `Document ID: ${id}    Revision: ${rev}`,
  `Process Owner: ${owner}    Status: Controlled copy`,
  "",
  "1. Purpose",
  "To define the controlled requirements for this process and the records it generates.",
  "",
  "2. Scope",
  "Applies to all personnel and equipment performing the activities described herein.",
  "",
  "3. Responsibilities",
  "The process owner maintains this document. Quality Assurance approves revisions.",
  "Personnel must read, understand, and follow the current revision before starting work.",
  "",
  "4. Records",
  "Records generated by this procedure are retained for a minimum of seven years.",
];

export const documentFiles: Record<string, SeedFile> = {
  "doc-1": pdf("SOP-001 Document Control Procedure Rev 4", docHeader("SOP-001", "4", "Noah Foster")),
  "doc-2": pdf("Change Control Log Rev 3", [
    "Change Control Log",
    "Revision history for controlled documents.",
    "",
    "Rev 3 | 2026-08-18 | Added deviation reporting section | Noah Foster",
    "Rev 2 | 2026-06-02 | Annual review, no technical change | Mila Gomez",
    "Rev 1 | 2026-01-20 | Initial issue | Mila Gomez",
  ]),
  "doc-3": pdf("Supplier Qualification Sheet Rev 1", docHeader("F-QS-001", "1", "Mila Gomez")),
  "doc-4": pdf("Quality Manual Rev 6", [
    "Quality Manual",
    "Revision: 6    Effective: 2026-01-01",
    "",
    "1. Quality Policy",
    "The organisation is committed to delivering products and services that consistently",
    "meet customer and regulatory requirements, and to continuously improving its QMS.",
    "",
    "2. Quality Objectives",
    "Reduce customer complaints by 25% year over year.",
    "Close 90% of corrective actions within their due date.",
    "Maintain calibration compliance above 98%.",
    "",
    "3. Management Responsibility",
    "Top management reviews this manual at least annually and ensures resources are available.",
  ]),
  "doc-5": pdf("Batch Manufacturing Record Template", docHeader("F-BMR-001", "2", "Daniel Kim")),
  "doc-6": pdf("Internal Audit Program 2026", [
    "Internal Audit Program 2026",
    "",
    "The audit cycle covers every QMS process at least once per calendar year.",
    "Auditors are independent of the area they audit.",
    "",
    "Q1  Document control, calibration",
    "Q2  Production, maintenance, CAPA",
    "Q3  Supplier management, training",
    "Q4  Traceability, complaint handling",
  ]),
  "doc-7": pdf("Deviation Handling Procedure Rev 3", docHeader("SOP-014", "3", "Elena Torres")),
  "doc-8": pdf("CAPA Effectiveness Verification SOP", docHeader("SOP-022", "1", "Chris Allen")),
  "doc-9": pdf("Environmental Monitoring Plan", docHeader("EMP-001", "2", "Sara Khan")),
  "doc-10": pdf("Personnel Training Record", docHeader("F-TR-001", "1", "Tom Brooks")),
  "doc-11": pdf("Risk Management File ISO 14971", [
    "Risk Management File",
    "Standard: ISO 14971:2019",
    "",
    "Risk 1  Contamination during filling",
    "  Severity 4  Occurrence 2  Detectability 3   RPN 24   Mitigation: segregated filling area",
    "",
    "Risk 2  Label mix-up between two products",
    "  Severity 5  Occurrence 1  Detectability 2   RPN 10   Mitigation: line clearance check",
    "",
    "Risk 3  Cold chain break in transit",
    "  Severity 4  Occurrence 3  Detectability 2   RPN 24   Mitigation: validated shipper, temp logger",
  ]),
  "doc-12": pdf("Calibration Schedule 2026", [
    "Calibration Schedule 2026",
    "",
    "Asset            Interval   Last due    Status",
    "Analytical balance  12 mo     2026-03-14  Complete",
    "pH meter            6 mo      2026-06-30  Complete",
    "Autoclave           12 mo     2026-09-28  Due",
    "Thermometer, bath   6 mo      2026-10-15  Scheduled",
    "Flow meter          12 mo     2026-12-01  Scheduled",
  ]),
  "doc-13": pdf("Complaint Handling Procedure Rev 2", docHeader("SOP-009", "2", "Elena Torres")),
  "doc-14": pdf("Cleaning Validation Protocol", docHeader("VP-004", "1", "Daniel Kim")),
  "doc-15": pdf("Good Distribution Practice Checklist", docHeader("GDP-001", "1", "Sara Khan")),
};

export const supplierAuditCsv = csv("supplier-audit-scorecard.csv", [
  ["Supplier", "Audit date", "Score", "Open findings", "Status"],
  ["NordChem GmbH", "2026-07-14", "88", "2", "Conditional"],
  ["Valora Ingredients", "2026-05-22", "94", "0", "Approved"],
  ["Meridian Packaging", "2026-08-05", "71", "6", "Under review"],
  ["Halden Polymers", "2026-06-11", "90", "1", "Approved"],
]);

export const capaTrendCsv = csv("capa-effectiveness-q3.csv", [
  ["Quarter", "Opened", "Closed", "On-time closure %"],
  ["Q1 2026", "18", "16", "88.9"],
  ["Q2 2026", "24", "19", "79.2"],
  ["Q3 2026", "21", "18", "85.7"],
]);

// Every record in every module gets a real, openable file so the attach panel
// has something to show across all five dashboards. Keyed by record id.
function filesFor(
  rows: readonly { id: string; title?: string; course?: string }[],
  prefix: string,
  section: string
): Record<string, SeedFile> {
  const out: Record<string, SeedFile> = {};
  for (const row of rows) {
    const title = row.title ?? row.course ?? "Record";
    out[row.id] = pdf(`${prefix} - ${title}`, [
      `${prefix}: ${title}`,
      "",
      `${section} evidence attached to this record.`,
      "Generated: 2026-09-29",
    ]);
  }
  return out;
}

const photo: SeedFile = {
  fileName: "evidence-photo.png",
  fileType: "image/png",
  fileSize: makePng().byteLength,
  fileData: makePng().toString("base64"),
};

export const capaFiles: Record<string, SeedFile> = {
  ...filesFor(recordsByModule.capa, "Corrective Action Plan", "CAPA"),
  "capa-2": capaTrendCsv,
};

export const ncFiles: Record<string, SeedFile> = {
  ...filesFor(recordsByModule.nonconformances, "Nonconformance Report", "Nonconformance"),
  "nc-2": photo,
  "nc-5": photo,
  "nc-10": photo,
};

export const auditFiles: Record<string, SeedFile> = {
  ...filesFor(recordsByModule.audits, "Audit Report", "Audit"),
  "audit-2": supplierAuditCsv,
};

export const trainingFiles: Record<string, SeedFile> = filesFor(
  recordsByModule.training,
  "Training Record",
  "Training"
);
